/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello Rajeev Buddy!!";
    }

    public static void main(String[] args) {
        Pallindrome p = new Pallindrome();
        boolean res = p.isPall("madam");

        System.out.println("is string 'madam' pallindrom? " + res);
    }
}
